<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Admin_MainMenu.aspx.cs" Inherits="Aula_Movil.Admin_MainMenu" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <center>
    <asp:GridView 
        ID="GridView1" runat="server" Height="217px" Width="557px"
        AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" AutoGenerateEditButton="True"
        OnRowEditing="Gr1_OnRowEditing" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowUpdating="GridView1_RowUpdating" >
        </asp:GridView>
    </center>
</asp:Content>
